require('dotenv').config();

const drunktankRole = "795125880363679745";
const tankChannel = "795125618957484052";
const logChannel = "795125578494640188";
const botMasterRole = "846036899523985449";
const serverID = "795115424634372147";
const tankUOM = "hours";
const tankDuration = "12";
const commandPrefix = ".";
const access_key = process.env.test_access_key;
const json_path = "C:/t/tankees.json";
const bot_name = "StevieBot";
const bypassGMU = ['775415118333870131','159985870458322944'];
const defaultStaffChat = "801188002486812712";
const writeMessageToDrunkTank = false;
const warnAuthorizedUsage = false;
const countedStrings = ['sip', 'burp', 'fart','vomit'];
const countedJsonPath = 'C:/t/sipcount.json';
const useDatabase = true;
const drunkTankCollection = "drunk-tank"
const sipCollection = "sips"
const databaseName = "tctest"

exports.drunktankRole = drunktankRole
exports.tankChannel = tankChannel
exports.logChannel = logChannel
exports.botMasterRole = botMasterRole
exports.tankUOM = tankUOM
exports.tankDuration = tankDuration
exports.commandPrefix = commandPrefix
exports.access_key = access_key
exports.json_path = json_path
exports.bot_name = bot_name
exports.serverID = serverID
exports.bypassGMU = bypassGMU
exports.defaultStaffChat = defaultStaffChat
exports.writeMessageToDrunkTank = writeMessageToDrunkTank;
exports.warnAuthorizedUsage = warnAuthorizedUsage;
exports.countedStrings = countedStrings;
exports.countedJsonPath = countedJsonPath;
exports.useDatabase = useDatabase;
exports.drunkTankCollection = drunkTankCollection;
exports.sipCollection = sipCollection;
exports.databaseName = databaseName;